day_or_night/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('mainapp.urls')),
    url(r'^', include('mainapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('mainapp.views',
    url(r'^(?P<document_id>[0-9]+)/$', 'detail', name='detail'),
    url(r'^$', 'upload', name='upload'),
)

mainapp/models.py
from django.db import models
from django.utils import timezone

class Document(models.Model):
    docfile = models.ImageField(upload_to='documents/%Y/%m/%d')
    source = models.CharField(max_length=200, default="")
    day_score = models.FloatField(default=0)
    created_at = models.DateTimeField(default=timezone.now)

class DocumentClassification(models.Model):
    document = models.ForeignKey(Document)
    score = models.FloatField(default=0)
    ip = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(default=timezone.now)

mainapp/forms.py
# -*- coding: utf-8 -*-
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

CHOICES = ((0.0, 'Night',), (1.0, 'Day',))
class ClassificationForm(forms.Form):
    choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES, label="Choice")

mainapp/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Document, DocumentClassification
from .forms import DocumentForm, ClassificationForm
from .views_utils import get_client_ip, get_lastest_documents, check_if_submited_list
from neuralnetwork import get

import imghdr


def upload(request):
    ip = get_client_ip(request)

    documents = get_lastest_documents()

    documents_submitions = check_if_submited_list(list(documents), ip)

    wrong_file = False

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile = request.FILES['docfile'], day_score = get(request.FILES['docfile']))
            newdoc.save()
            return HttpResponseRedirect(reverse('mainapp.views.detail', kwargs={'document_id':newdoc.id}))

    form = DocumentForm()

    return render(request, 'upload.html', {'documents': documents_submitions.items(), 'form': form, 'wrong_file':wrong_file})


def detail(request, document_id):
    ip = get_client_ip(request)

    document = Document.objects.get(id=document_id)
    documents = get_lastest_documents()

    documents_submitions = check_if_submited_list(list(documents)+[document], ip)

    if request.method == 'POST' and not documents_submitions[document]:
        form = ClassificationForm(request.POST)
        if form.is_valid():
            documents_submitions[document] = True
            score = request.POST.getlist('choice_field')[0]
            classification = DocumentClassification(document=document, score=score, ip=ip)
            classification.save()
    else:
        form = ClassificationForm()

    document_info = (document, documents_submitions[document])
    return render(request, 'detail.html', {'documents': documents_submitions.items(), 'form': form, 'document':document_info})

mainapp/templates/detail.html
{% extends "base.html" %}
{% load messages_filters %}

{% block content %}
<div class="col-md-4 col-md-offset-4 content-block">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-centered content-block-main">
                <div>
                    <img class="content-block-img" src="{{ document.0.docfile.url }}">
                </div>

                {% if not document.1 %}
                <form action="{% url 'detail' document_id=document.0.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div id="id_choice_field" class="btn-group choice-input-group" data-toggle="buttons">
                        <label class="btn btn-warning choice-field-input">
                            <input type="radio" name="choice_field" id="id_choice_field_1" value="1.0" autocomplete="off" checked>DAY</input>
                        </label>
                        <label class="btn btn-primary choice-field-input">
                            <input type="radio" name="choice_field" id="id_choice_field_0" value="0.0" autocomplete="off">NIGHT</input>
                        </label>
                    </div>
                    <input class="btn btn-success btn-choice-submit" type="submit" value="Send" />
                </form>


                {% else %}
                    <div class="image-info-label label-{% if document.0.day_score|get_day_or_night_from_score == "DAY" %}warning{% else %}primary{% endif %}">
                        <div class="badge image-info-label-badge">
                            {{ document.0.day_score|get_day_or_night_from_score }}
                        </div>
                        <div class="badge image-info-label-badge" data-toggle="tooltip" data-html="true" data-placement="bottom" title="Systems result.</br>Score close to 0.0 means night.</br>Score close to 1.0 means day.">
                            score: {{ document.0.day_score|floatformat:3  }}
                        </div>
                        <div class="badge image-info-label-badge bg-success fg-white" data-html="true" data-toggle="tooltip" data-placement="bottom" title="Your choice">
                            {{ document.1.day_score|get_day_or_night_from_score }}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block gallery %}
    {% include "gallery.html" with documents=documents %}
{% endblock gallery %}

mainapp/templates/gallery.html
{% load messages_filters %}
{% block gallery %}
{% if documents %}
    <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                {% for document in documents %}
                <div class="col-md-3">
                    <div class="image-icon">
                        <a href="{% url 'detail' document_id=document.0.id %}">
                            <img class="image-icon-img" src="{{ document.0.docfile.url }}">
                        </a>
                    </div>
                    <div class="image-info-label label-{% if not document.1 %}default{% elif document.0.day_score|get_day_or_night_from_score == "DAY" %}warning{% else %}primary{% endif %}">
                        {% if document.1 %}
                            <div class="badge image-info-label-badge">
                                {{ document.0.day_score|get_day_or_night_from_score }}
                            </div>
                            <div class="badge image-info-label-badge" data-toggle="tooltip" data-html="true" data-placement="bottom" title="Systems result.</br>Score close to 0.0 means night.</br>Score close to 1.0 means day.">
                                score: {{ document.0.day_score|floatformat:3  }}
                            </div>
                            <div class="badge image-info-label-badge bg-success fg-white" data-html="true" data-toggle="tooltip" data-placement="bottom" title="Your choice">
                                {{ document.1.day_score|get_day_or_night_from_score }}
                            </div>
                        {% else %}
                            <div class="badge image-info-label-badge" data-html="true" data-toggle="tooltip" data-placement="bottom" title="You need to send your anwser first to see how the System responded.">
                                ?
                            </div>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                </div>
                <div class="panel-heading"><a href="/" class="btn btn-primary"><i class="fa fa-home"></i> Home</a></div>
            </div>
        </div>
    <div class="col-md-2"></div>
{% else %}
    <p>No documents.</p>
{% endif %}
{% endblock gallery %}

<script type = 'text/javascript'>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
</script>

mainapp/templates/upload.html
{% extends "base.html" %}
{% load messages_filters %}
{% block content %}
<div class="col-md-4 col-md-offset-4 content-block">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-centered content-block-main" style="margin-bottom:23px">
                <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.docfile.errors }}
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-preview thumbnail content-block-img" data-trigger="fileinput" style="width:440px"></div>
                        <div>
                            <span class="btn btn-default btn-file btn-upload">
                                <span class="fileinput-new">Select image</span>
                                <span class="fileinput-exists">Change</span>
                                <input id="id_docfile" name="docfile" type="file">
                            </span>
                            <button class="btn btn-primary btn-upload" type="submit"><i class="fa fa-upload"></i> Upload</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block gallery %}
    {% include "gallery.html" with documents=documents %}
{% endblock gallery %}

<script type = 'text/javascript'>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

</script>

templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Test</title>
        {% include "base_header.html" %}
    </head>
    <body>
        <div class="row">
            <div class="row">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="row">
                {% block gallery %}
                {% endblock gallery %}
            </div>
        </div>
    </body>
</html>

templates/base_header.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/jasny-bootstrap.min.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/mainapp-style.css' %}" />

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jasny-bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootbox.min.js' %}"></script>